packaging_format = 2

id = "hydrogen"
name = "Hydrogen"
description.en = "Web client for Matrix"
description.fr = "Client web pour Matrix"

version = "0.4.1~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "Apache-2.0"
website = "https://matrix.org/ecosystem/clients/hydrogen/"
demo = "https://hydrogen.element.io/"
code = "https://github.com/vector-im/hydrogen-web"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.default_server]
    ask.en = "Choose a default server"
    ask.fr = "Choisissez un serveur par défault"
    type = "string"
    example = "my-matrix-server.tld"
    default = "matrix.org"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/vector-im/hydrogen-web/releases/download/v0.4.1/hydrogen-web-0.4.1.tar.gz"
        sha256 = "b4ba42a13b5cec1e447408959f2f9dc00df431a68b3e457c569fd1d0bad8042d"
        autoupdate.strategy = "latest_github_tag"

    [resources.ports]
    
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
