packaging_format = 2

id = "hydrogen"
name = "Hydrogen"
description.en = "Web client for Matrix"
description.fr = "Client web pour Matrix"

version = "0.5.1~ynh1"

maintainers = []

[upstream]
license = "Apache-2.0"
website = "https://matrix.org/ecosystem/clients/hydrogen/"
demo = "https://hydrogen.element.io/"
code = "https://github.com/vector-im/hydrogen-web"

[integration]
yunohost = ">= 11.2.27"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.default_server]
    ask.en = "Choose a default server"
    ask.fr = "Choisissez un serveur par défault"
    type = "string"
    example = "my-matrix-server.tld"
    default = "matrix.org"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/vector-im/hydrogen-web/archive/refs/tags/v0.5.1.tar.gz"
        sha256 = "f47e9a6116639eac957bb0ee3621a4e0ef8bbb7b300d2fd149923197f4284c2f"
        autoupdate.strategy = "latest_github_tag"

    [resources.ports]
    
    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
