packaging_format = 2

id = "hydrogen"
name = "Hydrogen"
description.en = "Web client for Matrix"
description.fr = "Client web pour Matrix"

version = "0.3.7~ynh2"

maintainers = ["eric_G"]

[upstream]
license = "Apache-2.0"
website = "https://matrix.org/docs/projects/client/hydrogen"
demo = "https://hydrogen.element.io/"
code = "https://github.com/vector-im/hydrogen-web"

[integration]
yunohost = ">= 11.1.15"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"
    full_domain = true

    [install.default_server]
    ask.en = "Choose a default server"
    ask.fr = "Choisissez un serveur par défault"
    type = "string"
    example = "my-matrix-server.tld"
    default = "matrix.org"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/vector-im/hydrogen-web/releases/download/v0.3.7/hydrogen-web-0.3.7.tar.gz"
        sha256 = "9a00efba9d839c96cd2f05e7bf597acb5e51e50560c56ce6e72a58a5019b376b"

    [resources.ports]
    
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
