packaging_format = 2

id = "hydrogen"
name = "Hydrogen"
description.en = "Web client for Matrix"
description.fr = "Client web pour Matrix"

version = "0.4.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "Apache-2.0"
website = "https://matrix.org/docs/projects/client/hydrogen"
demo = "https://hydrogen.element.io/"
code = "https://github.com/vector-im/hydrogen-web"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.default_server]
    ask.en = "Choose a default server"
    ask.fr = "Choisissez un serveur par défault"
    type = "string"
    example = "my-matrix-server.tld"
    default = "matrix.org"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/vector-im/hydrogen-web/releases/download/v0.4.0/hydrogen-web-0.4.0.tar.gz"
        sha256 = "f9fbc4a03446dd9c41b88dfbf0f93239e5ee524516751b909325d7c617b7dbfa"
        autoupdate.strategy = "latest_github_tag"

    [resources.ports]
    
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
